// student

const student8AB=[{
    "firstName": "Rahul",
    "middleName": "Anil",
    "surname": "Sharma",
    "fullName": "Rahul Anil Sharma",
    "fatherName": "Anil Suresh Sharma",
    "motherName": "Sunita Sharma",
    "birthDate": "2010-05-12",
    "email": "rahul.sharma@example.com",
    "gender": "Male",
    "mobile": 9876543210,
    "aadhar": 123456789012,
    "nameAsPerAadhar": "Rahul Sharma",
    "GR": 1,
    "bloodgroup": "B+",
    "cast": "General",
    "standard": 8,
    "classGroup": "8A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName":"Manishaben Maheshbhai Upadhyay",
    "address": {
      "village": "Village Name Q",
      "taluko": "Taluko Name Q",
      "district": "District Name Q",
      "pincode": 123456
    },
    "rollNumber": 1,
    "password":"Rahul@123"
  },
  {
    "firstName": "Anjali",
    "middleName": "Ramesh",
    "surname": "Rai",
    "fullName": "Anjali Ramesh Rai",
    "fatherName": "Ramesh Brijesh Rai",
    "motherName": "Anita Rai",
    "birthDate": "2010-05-12",
    "email": "rahul.sharma@example.com",
    "gender": "Female",
    "mobile": 9876543210,
    "aadhar": 123456789013,
    "nameAsPerAadhar": "Anjali Rai",
    "GR": 2,
    "bloodgroup": "B+",
    "cast": "General",
    "standard": 8,
    "classGroup": "8A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName":"Manishaben Maheshbhai Upadhyay",
    "address": {
      "village": "Village Name R",
      "taluko": "Taluko Name R",
      "district": "District Name R",
      "pincode": 123457
    },
    "rollNumber": 2,
    "password":"Anjali@123"
  }
]

const student7AB=[

    {
      "firstName": "Saurabh",
      "middleName": "Kumar",
      "surname": "Yadav",
      "fullName": "Saurabh Kumar Yadav",
      "fatherName": "Rajesh Yadav",
      "motherName": "Rekha Yadav",
      "birthDate": "2011-06-10",
      "email": "saurabh.yadav@example.com",
      "gender": "Male",
      "mobile": 9876543213,
      "aadhar": 123456789016,
      "nameAsPerAadhar": "Saurabh Yadav",
      "GR": 5,
      "bloodgroup": "O+",
      "cast": "OBC",
      "standard": 7,
      "classGroup": "7A",
      "religion": "Hindu",
      "physicallyHandicapped": "No",
      "role": "Student",
      "classTeacherName": "Rajesh Mahesh Shah",
      "address": {
        "village": "Village Name C",
        "taluko": "Taluko Name C",
        "district": "District Name C",
        "pincode": 123459
      },
      "rollNumber": 1,
      "password": "Saurabh@123"
    },
    {
      "firstName": "Simran",
      "middleName": "Rani",
      "surname": "Mehta",
      "fullName": "Simran Rani Mehta",
      "fatherName": "Rajendra Mehta",
      "motherName": "Sangeeta Mehta",
      "birthDate": "2011-05-05",
      "email": "simran.mehta@example.com",
      "gender": "Female",
      "mobile": 9876543214,
      "aadhar": 123456789017,
      "nameAsPerAadhar": "Simran Mehta",
      "GR": 6,
      "bloodgroup": "A-",
      "cast": "General",
      "standard": 7,
      "classGroup": "7A",
      "religion": "Hindu",
      "physicallyHandicapped": "No",
      "role": "Student",
      "classTeacherName": "Rajesh Mahesh Shah",
      "address": {
        "village": "Village Name D",
        "taluko": "Taluko Name D",
        "district": "District Name D",
        "pincode": 123460
      },
      "rollNumber": 2,
      "password": "Simran@123"
    },
    {
      "firstName": "Vijay",
      "middleName": "Suresh",
      "surname": "Patel",
      "fullName": "Vijay Suresh Patel",
      "fatherName": "Mahesh Patel",
      "motherName": "Nisha Patel",
      "birthDate": "2011-04-15",
      "email": "vijay.patel@example.com",
      "gender": "Male",
      "mobile": 9876543215,
      "aadhar": 123456789018,
      "nameAsPerAadhar": "Vijay Patel",
      "GR": 7,
      "bloodgroup": "B-",
      "cast": "SC",
      "standard": 7,
      "classGroup": "7B",
      "religion": "Hindu",
      "physicallyHandicapped": "No",
      "role": "Student",
      "classTeacherName": "Seema Vinod Patel",
      "address": {
        "village": "Village Name E",
        "taluko": "Taluko Name E",
        "district": "District Name E",
        "pincode": 123461
      },
      "rollNumber": 3,
      "password": "Vijay@123"
    },
    {
      "firstName": "Asha",
      "middleName": "Raj",
      "surname": "Desai",
      "fullName": "Asha Raj Desai",
      "fatherName": "Vikram Desai",
      "motherName": "Seema Desai",
      "birthDate": "2011-09-25",
      "email": "asha.desai@example.com",
      "gender": "Female",
      "mobile": 9876543216,
      "aadhar": 123456789019,
      "nameAsPerAadhar": "Asha Desai",
      "GR": 8,
      "bloodgroup": "O-",
      "cast": "ST",
      "standard": 7,
      "classGroup": "7B",
      "religion": "Hindu",
      "physicallyHandicapped": "No",
      "role": "Student",
      "classTeacherName": "Seema Vinod Patel",
      "address": {
        "village": "Village Name F",
        "taluko": "Taluko Name F",
        "district": "District Name F",
        "pincode": 123462
      },
      "rollNumber": 4,
      "password": "Asha@123"
    }
  ];
  
const student6AB=[
  {
    "firstName": "Ravi",
    "middleName": "Raj",
    "surname": "Shukla",
    "fullName": "Ravi Raj Shukla",
    "fatherName": "Suresh Shukla",
    "motherName": "Neelam Shukla",
    "birthDate": "2012-01-10",
    "email": "ravi.shukla@example.com",
    "gender": "Male",
    "mobile": 9876543217,
    "aadhar": 123456789020,
    "nameAsPerAadhar": "Ravi Shukla",
    "GR": 9,
    "bloodgroup": "B+",
    "cast": "OBC",
    "standard": 6,
    "classGroup": "6A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Amit Rakesh Joshi",
    "address": {
      "village": "Village Name G",
      "taluko": "Taluko Name G",
      "district": "District Name G",
      "pincode": 123463
    },
    "rollNumber": 1,
    "password": "Ravi@123"
  },
  {
    "firstName": "Priya",
    "middleName": "Suman",
    "surname": "Gupta",
    "fullName": "Priya Suman Gupta",
    "fatherName": "Vikram Gupta",
    "motherName": "Sushma Gupta",
    "birthDate": "2012-03-20",
    "email": "priya.gupta@example.com",
    "gender": "Female",
    "mobile": 9876543218,
    "aadhar": 123456789021,
    "nameAsPerAadhar": "Priya Gupta",
    "GR": 10,
    "bloodgroup": "A+",
    "cast": "General",
    "standard": 6,
    "classGroup": "6A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Amit Rakesh Joshi",
    "address": {
      "village": "Village Name H",
      "taluko": "Taluko Name H",
      "district": "District Name H",
      "pincode": 123464
    },
    "rollNumber": 2,
    "password": "Priya@123"
  },
  {
    "firstName": "Manish",
    "middleName": "Kishore",
    "surname": "Chauhan",
    "fullName": "Manish Kishore Chauhan",
    "fatherName": "Suresh Chauhan",
    "motherName": "Rekha Chauhan",
    "birthDate": "2012-04-12",
    "email": "manish.chauhan@example.com",
    "gender": "Male",
    "mobile": 9876543219,
    "aadhar": 123456789022,
    "nameAsPerAadhar": "Manish Chauhan",
    "GR": 11,
    "bloodgroup": "AB+",
    "cast": "SC",
    "standard": 6,
    "classGroup": "6B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Manisha Kiran Kapadia",
    "address": {
      "village": "Village Name I",
      "taluko": "Taluko Name I",
      "district": "District Name I",
      "pincode": 123465
    },
    "rollNumber": 3,
    "password": "Manish@123"
  },
  {
    "firstName": "Neelam",
    "middleName": "Nisha",
    "surname": "Rathod",
    "fullName": "Neelam Nisha Rathod",
    "fatherName": "Jayant Rathod",
    "motherName": "Madhavi Rathod",
    "birthDate": "2012-07-18",
    "email": "neelam.rathod@example.com",
    "gender": "Female",
    "mobile": 9876543220,
    "aadhar": 123456789023,
    "nameAsPerAadhar": "Neelam Rathod",
    "GR": 12,
    "bloodgroup": "O+",
    "cast": "ST",
    "standard": 6,
    "classGroup": "6B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Manisha Kiran Kapadia",
    "address": {
      "village": "Village Name J",
      "taluko": "Taluko Name J",
      "district": "District Name J",
      "pincode": 123466
    },
    "rollNumber": 4,
    "password": "Neelam@123"
  }
]

const student5AB=[
  {
    "firstName": "Siddhi",
    "middleName": "Kiran",
    "surname": "Patel",
    "fullName": "Siddhi Kiran Patel",
    "fatherName": "Ramesh Patel",
    "motherName": "Pooja Patel",
    "birthDate": "2013-09-05",
    "email": "siddhi.patel@example.com",
    "gender": "Female",
    "mobile": 9876543221,
    "aadhar": 123456789024,
    "nameAsPerAadhar": "Siddhi Patel",
    "GR": 13,
    "bloodgroup": "O-",
    "cast": "General",
    "standard": 5,
    "classGroup": "5A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kiran Ramesh Mehta",
    "address": {
      "village": "Village Name K",
      "taluko": "Taluko Name K",
      "district": "District Name K",
      "pincode": 123467
    },
    "rollNumber": 1,
    "password": "Siddhi@123"
  },
  {
    "firstName": "Vishal",
    "middleName": "Rajesh",
    "surname": "Singh",
    "fullName": "Vishal Rajesh Singh",
    "fatherName": "Rajesh Singh",
    "motherName": "Seema Singh",
    "birthDate": "2013-11-15",
    "email": "vishal.singh@example.com",
    "gender": "Male",
    "mobile": 9876543222,
    "aadhar": 123456789025,
    "nameAsPerAadhar": "Vishal Singh",
    "GR": 14,
    "bloodgroup": "AB-",
    "cast": "OBC",
    "standard": 5,
    "classGroup": "5A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kiran Ramesh Mehta",
    "address": {
      "village": "Village Name L",
      "taluko": "Taluko Name L",
      "district": "District Name L",
      "pincode": 123468
    },
    "rollNumber": 2,
    "password": "Vishal@123"
  },
  {
    "firstName": "Ravi",
    "middleName": "Dinesh",
    "surname": "Sharma",
    "fullName": "Ravi Dinesh Sharma",
    "fatherName": "Dinesh Sharma",
    "motherName": "Geeta Sharma",
    "birthDate": "2013-02-25",
    "email": "ravi.sharma@example.com",
    "gender": "Male",
    "mobile": 9876543223,
    "aadhar": 123456789026,
    "nameAsPerAadhar": "Ravi Sharma",
    "GR": 15,
    "bloodgroup": "B-",
    "cast": "SC",
    "standard": 5,
    "classGroup": "5B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Priya Dinesh Desai",
    "address": {
      "village": "Village Name M",
      "taluko": "Taluko Name M",
      "district": "District Name M",
      "pincode": 123469
    },
    "rollNumber": 3,
    "password": "Ravi@123"
  },
  {
    "firstName": "Madhavi",
    "middleName": "Suresh",
    "surname": "Joshi",
    "fullName": "Madhavi Suresh Joshi",
    "fatherName": "Suresh Joshi",
    "motherName": "Pooja Joshi",
    "birthDate": "2013-06-10",
    "email": "madhavi.joshi@example.com",
    "gender": "Female",
    "mobile": 9876543224,
    "aadhar": 123456789027,
    "nameAsPerAadhar": "Madhavi Joshi",
    "GR": 16,
    "bloodgroup": "O+",
    "cast": "General",
    "standard": 5,
    "classGroup": "5B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Priya Dinesh Desai",
    "address": {
      "village": "Village Name N",
      "taluko": "Taluko Name N",
      "district": "District Name N",
      "pincode": 123470
    },
    "rollNumber": 4,
    "password": "Madhavi@123"
  }
]

const student4AB=[
  {
    "firstName": "Aarav",
    "middleName": "Ravi",
    "surname": "Patel",
    "fullName": "Aarav Ravi Patel",
    "fatherName": "Ravi Patel",
    "motherName": "Suman Patel",
    "birthDate": "2014-08-12",
    "email": "aarav.patel@example.com",
    "gender": "Male",
    "mobile": 9876543231,
    "aadhar": 123456789028,
    "nameAsPerAadhar": "Aarav Patel",
    "GR": 17,
    "bloodgroup": "O+",
    "cast": "General",
    "standard": 4,
    "classGroup": "4A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Ravi Mahesh Patel",
    "address": {
      "village": "Village Name O",
      "taluko": "Taluko Name O",
      "district": "District Name O",
      "pincode": 123471
    },
    "rollNumber": 1,
    "password": "Aarav@123"
  },
  {
    "firstName": "Meera",
    "middleName": "Ravi",
    "surname": "Desai",
    "fullName": "Meera Ravi Desai",
    "fatherName": "Ravi Desai",
    "motherName": "Anjali Desai",
    "birthDate": "2014-01-19",
    "email": "meera.desai@example.com",
    "gender": "Female",
    "mobile": 9876543232,
    "aadhar": 123456789029,
    "nameAsPerAadhar": "Meera Desai",
    "GR": 18,
    "bloodgroup": "A+",
    "cast": "OBC",
    "standard": 4,
    "classGroup": "4A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Ravi Mahesh Patel",
    "address": {
      "village": "Village Name P",
      "taluko": "Taluko Name P",
      "district": "District Name P",
      "pincode": 123472
    },
    "rollNumber": 2,
    "password": "Meera@123"
  },
  {
    "firstName": "Karan",
    "middleName": "Rajesh",
    "surname": "Shah",
    "fullName": "Karan Rajesh Shah",
    "fatherName": "Rajesh Shah",
    "motherName": "Nisha Shah",
    "birthDate": "2014-07-20",
    "email": "karan.shah@example.com",
    "gender": "Male",
    "mobile": 9876543233,
    "aadhar": 123456789030,
    "nameAsPerAadhar": "Karan Shah",
    "GR": 19,
    "bloodgroup": "B+",
    "cast": "General",
    "standard": 4,
    "classGroup": "4B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Ankita Rajesh Shah",
    "address": {
      "village": "Village Name Q",
      "taluko": "Taluko Name Q",
      "district": "District Name Q",
      "pincode": 123473
    },
    "rollNumber": 3,
    "password": "Karan@123"
  },
  {
    "firstName": "Sanya",
    "middleName": "Rajesh",
    "surname": "Patel",
    "fullName": "Sanya Rajesh Patel",
    "fatherName": "Rajesh Patel",
    "motherName": "Priya Patel",
    "birthDate": "2014-05-03",
    "email": "sanya.patel@example.com",
    "gender": "Female",
    "mobile": 9876543234,
    "aadhar": 123456789031,
    "nameAsPerAadhar": "Sanya Patel",
    "GR": 20,
    "bloodgroup": "AB+",
    "cast": "SC",
    "standard": 4,
    "classGroup": "4B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Ankita Rajesh Shah",
    "address": {
      "village": "Village Name R",
      "taluko": "Taluko Name R",
      "district": "District Name R",
      "pincode": 123474
    },
    "rollNumber": 4,
    "password": "Sanya@123"
  }
]

const student3AB=[
  {
    "firstName": "Ishaan",
    "middleName": "Kiran",
    "surname": "Mehta",
    "fullName": "Ishaan Kiran Mehta",
    "fatherName": "Kiran Mehta",
    "motherName": "Priya Mehta",
    "birthDate": "2015-10-10",
    "email": "ishaan.mehta@example.com",
    "gender": "Male",
    "mobile": 9876543235,
    "aadhar": 123456789032,
    "nameAsPerAadhar": "Ishaan Mehta",
    "GR": 21,
    "bloodgroup": "O-",
    "cast": "General",
    "standard": 3,
    "classGroup": "3A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kiran Suresh Mehta",
    "address": {
      "village": "Village Name S",
      "taluko": "Taluko Name S",
      "district": "District Name S",
      "pincode": 123475
    },
    "rollNumber": 1,
    "password": "Ishaan@123"
  },
  {
    "firstName": "Tanvi",
    "middleName": "Kiran",
    "surname": "Patel",
    "fullName": "Tanvi Kiran Patel",
    "fatherName": "Kiran Patel",
    "motherName": "Sonia Patel",
    "birthDate": "2015-02-28",
    "email": "tanvi.patel@example.com",
    "gender": "Female",
    "mobile": 9876543236,
    "aadhar": 123456789033,
    "nameAsPerAadhar": "Tanvi Patel",
    "GR": 22,
    "bloodgroup": "A-",
    "cast": "OBC",
    "standard": 3,
    "classGroup": "3A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kiran Suresh Mehta",
    "address": {
      "village": "Village Name T",
      "taluko": "Taluko Name T",
      "district": "District Name T",
      "pincode": 123476
    },
    "rollNumber": 2,
    "password": "Tanvi@123"
  },
  {
    "firstName": "Rohan",
    "middleName": "Vishal",
    "surname": "Joshi",
    "fullName": "Rohan Vishal Joshi",
    "fatherName": "Vishal Joshi",
    "motherName": "Neha Joshi",
    "birthDate": "2015-12-01",
    "email": "rohan.joshi@example.com",
    "gender": "Male",
    "mobile": 9876543237,
    "aadhar": 123456789034,
    "nameAsPerAadhar": "Rohan Joshi",
    "GR": 23,
    "bloodgroup": "B-",
    "cast": "SC",
    "standard": 3,
    "classGroup": "3B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Vishal Manoj Joshi",
    "address": {
      "village": "Village Name U",
      "taluko": "Taluko Name U",
      "district": "District Name U",
      "pincode": 123477
    },
    "rollNumber":3,
    "password": "Rohan@123"
  },
  {
    "firstName": "Diya",
    "middleName": "Vishal",
    "surname": "Sharma",
    "fullName": "Diya Vishal Sharma",
    "fatherName": "Vishal Sharma",
    "motherName": "Meera Sharma",
    "birthDate": "2015-07-14",
    "email": "diya.sharma@example.com",
    "gender": "Female",
    "mobile": 9876543238,
    "aadhar": 123456789035,
    "nameAsPerAadhar": "Diya Sharma",
    "GR": 24,
    "bloodgroup": "AB-",
    "cast": "General",
    "standard": 3,
    "classGroup": "3B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Vishal Manoj Joshi",
    "address": {
      "village": "Village Name V",
      "taluko": "Taluko Name V",
      "district": "District Name V",
      "pincode": 123478
    },
    "rollNumber": 4,
    "password": "Diya@123"
  }
]


const student2AB=[
  {
    "firstName": "Aarav",
    "middleName": "Neha",
    "surname": "Sharma",
    "fullName": "Aarav Neha Sharma",
    "fatherName": "Ravi Sharma",
    "motherName": "Neha Sharma",
    "birthDate": "2016-05-15",
    "email": "aarav.sharma@example.com",
    "gender": "Male",
    "mobile": 9876543241,
    "aadhar": 123456789036,
    "nameAsPerAadhar": "Aarav Sharma",
    "GR": 31,
    "bloodgroup": "O+",
    "cast": "General",
    "standard": 2,
    "classGroup": "2A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Neha Ravi Sharma",
    "address": {
      "village": "Village Name A",
      "taluko": "Taluko Name A",
      "district": "District Name A",
      "pincode": 123479
    },
    "rollNumber": 1,
    "password": "Aarav@123"
  },
  {
    "firstName": "Saanvi",
    "middleName": "Neha",
    "surname": "Singh",
    "fullName": "Saanvi Neha Singh",
    "fatherName": "Ravi Singh",
    "motherName": "Neha Singh",
    "birthDate": "2016-08-20",
    "email": "saanvi.singh@example.com",
    "gender": "Female",
    "mobile": 9876543242,
    "aadhar": 123456789037,
    "nameAsPerAadhar": "Saanvi Singh",
    "GR": 32,
    "bloodgroup": "B+",
    "cast": "OBC",
    "standard": 2,
    "classGroup": "2A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Neha Ravi Sharma",
    "address": {
      "village": "Village Name B",
      "taluko": "Taluko Name B",
      "district": "District Name B",
      "pincode": 123480
    },
    "rollNumber": 2,
    "password": "Saanvi@123"
  },
  {
    "firstName": "Vivan",
    "middleName": "Anuj",
    "surname": "Verma",
    "fullName": "Vivan Anuj Verma",
    "fatherName": "Sanjay Verma",
    "motherName": "Rita Verma",
    "birthDate": "2016-01-05",
    "email": "vivan.verma@example.com",
    "gender": "Male",
    "mobile": 9876543243,
    "aadhar": 123456789038,
    "nameAsPerAadhar": "Vivan Verma",
    "GR": 41,
    "bloodgroup": "A+",
    "cast": "SC",
    "standard": 2,
    "classGroup": "2B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Anuj Sanjay Verma",
    "address": {
      "village": "Village Name C",
      "taluko": "Taluko Name C",
      "district": "District Name C",
      "pincode": 123481
    },
    "rollNumber": 3,
    "password": "Vivan@123"
  },
  {
    "firstName": "Ishita",
    "middleName": "Anuj",
    "surname": "Gupta",
    "fullName": "Ishita Anuj Gupta",
    "fatherName": "Sanjay Gupta",
    "motherName": "Pooja Gupta",
    "birthDate": "2016-09-12",
    "email": "ishita.gupta@example.com",
    "gender": "Female",
    "mobile": 9876543244,
    "aadhar": 123456789039,
    "nameAsPerAadhar": "Ishita Gupta",
    "GR": 42,
    "bloodgroup": "AB+",
    "cast": "General",
    "standard": 2,
    "classGroup": "2B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Anuj Sanjay Verma",
    "address": {
      "village": "Village Name D",
      "taluko": "Taluko Name D",
      "district": "District Name D",
      "pincode": 123482
    },
    "rollNumber": 4,
    "password": "Ishita@123"
  }
]

const student1AB=[
  {
    "firstName": "Ayaan",
    "middleName": "Pooja",
    "surname": "Goyal",
    "fullName": "Ayaan Pooja Goyal",
    "fatherName": "Mahendra Goyal",
    "motherName": "Pooja Goyal",
    "birthDate": "2017-04-10",
    "email": "ayaan.goyal@example.com",
    "gender": "Male",
    "mobile": 9876543251,
    "aadhar": 123456789040,
    "nameAsPerAadhar": "Ayaan Goyal",
    "GR": 51,
    "bloodgroup": "O+",
    "cast": "General",
    "standard": 1,
    "classGroup": "1A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Pooja Mahendra Goyal",
    "address": {
      "village": "Village Name E",
      "taluko": "Taluko Name E",
      "district": "District Name E",
      "pincode": 123483
    },
    "rollNumber": 1,
    "password": "Ayaan@123"
  },
  {
    "firstName": "Diya",
    "middleName": "Pooja",
    "surname": "Mehta",
    "fullName": "Diya Pooja Mehta",
    "fatherName": "Mahendra Mehta",
    "motherName": "Pooja Mehta",
    "birthDate": "2017-06-15",
    "email": "diya.mehta@example.com",
    "gender": "Female",
    "mobile": 9876543252,
    "aadhar": 123456789041,
    "nameAsPerAadhar": "Diya Mehta",
    "GR": 52,
    "bloodgroup": "A+",
    "cast": "General",
    "standard": 1,
    "classGroup": "1A",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Pooja Mahendra Goyal",
    "address": {
      "village": "Village Name F",
      "taluko": "Taluko Name F",
      "district": "District Name F",
      "pincode": 123484
    },
    "rollNumber": 2,
    "password": "Diya@123"
  },
  {
    "firstName": "Ravi",
    "middleName": "Arun",
    "surname": "Jain",
    "fullName": "Ravi Arun Jain",
    "fatherName": "Vinod Jain",
    "motherName": "Suman Jain",
    "birthDate": "2017-01-18",
    "email": "ravi.jain@example.com",
    "gender": "Male",
    "mobile": 9876543253,
    "aadhar": 123456789042,
    "nameAsPerAadhar": "Ravi Jain",
    "GR": 61,
    "bloodgroup": "B+",
    "cast": "OBC",
    "standard": 1,
    "classGroup": "1B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Arun Vinod Jain",
    "address": {
      "village": "Village Name G",
      "taluko": "Taluko Name G",
      "district": "District Name G",
      "pincode": 123485
    },
    "rollNumber": 3,
    "password": "Ravi@123"
  },
  {
    "firstName": "Ananya",
    "middleName": "Arun",
    "surname": "Sharma",
    "fullName": "Ananya Arun Sharma",
    "fatherName": "Vinod Sharma",
    "motherName": "Anjali Sharma",
    "birthDate": "2017-07-22",
    "email": "ananya.sharma@example.com",
    "gender": "Female",
    "mobile": 9876543254,
    "aadhar": 123456789043,
    "nameAsPerAadhar": "Ananya Sharma",
    "GR": 62,
    "bloodgroup": "AB+",
    "cast": "General",
    "standard": 1,
    "classGroup": "1B",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Arun Vinod Jain",
    "address": {
      "village": "Village Name H",
      "taluko": "Taluko Name H",
      "district": "District Name H",
      "pincode": 123486
    },
    "rollNumber": 4,
    "password": "Ananya@123"
  }
]

const student0=[
  {
    "firstName": "Ishaan",
    "middleName": "Kavita",
    "surname": "Chaudhary",
    "fullName": "Ishaan Kavita Chaudhary",
    "fatherName": "Rajendra Chaudhary",
    "motherName": "Kavita Chaudhary",
    "birthDate": "2019-08-10",
    "email": "ishaan.chaudhary@example.com",
    "gender": "Male",
    "mobile": 9876543201,
    "aadhar": 123456789050,
    "nameAsPerAadhar": "Ishaan Chaudhary",
    "GR": 101,
    "bloodgroup": "O-",
    "cast": "General",
    "standard": 0,
    "classGroup": "0",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kavita Rajendra Chaudhary",
    "address": {
      "village": "Village Name I",
      "taluko": "Taluko Name I",
      "district": "District Name I",
      "pincode": 123487
    },
    "rollNumber": 1,
    "password": "Ishaan@123"
  },
  {
    "firstName": "Aarav",
    "middleName": "Kavita",
    "surname": "Patel",
    "fullName": "Aarav Kavita Patel",
    "fatherName": "Rajendra Patel",
    "motherName": "Kavita Patel",
    "birthDate": "2019-09-15",
    "email": "aarav.patel@example.com",
    "gender": "Male",
    "mobile": 9876543202,
    "aadhar": 123456789051,
    "nameAsPerAadhar": "Aarav Patel",
    "GR": 102,
    "bloodgroup": "A-",
    "cast": "General",
    "standard": 0,
    "classGroup": "0",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Student",
    "classTeacherName": "Kavita Rajendra Chaudhary",
    "address": {
      "village": "Village Name J",
      "taluko": "Taluko Name J",
      "district": "District Name J",
      "pincode": 123488
    },
    "rollNumber": 2,
    "password": "Aarav@123"
  }
]
  const teacher8A={ 
    "firstName": "Manisha",
    "middleName": "Mahesh",
    "surname": "Upadhyay",
    "fullName": "Manishaben Maheshbhai Upadhyay",
    "fatherName": "Mahesh Upadhyay",
    "motherName": "Hetal Upadhyay",
    "birthDate": "1995-05-10",
    "email": "manisha.upadhyay@email.com",
    "gender": "Female",
    "mobile": 9856565656,
    "aadhar": 554567890122,
    "nameAsPerAadhar": "Manisha Mahesh Upadhyay",
    "bloodgroup": "AB+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village Name",
      "taluko": "Taluko Name",
      "district": "District Name",
      "pincode": 123456
    },
    "teachingStandard":"8A",
    "teacherCode":1,
    "password":"Manisha@123"
  }

  const teacher8B=
  { 
    "firstName": "Sangita",
    "middleName": "Ramsinh",
    "surname": "Rathod",
    "fullName": "Sangita Ramsinh Rathod",
    "fatherName": "Ramsinh Ajitsinh Rathod",
    "motherName": "Hetal Upadhyay",
    "birthDate": "1995-05-10",
    "email": "sangita.ramsinh@email.com",
    "gender": "Female",
    "mobile": 9856565656,
    "aadhar": 554567891124,
    "nameAsPerAadhar": "Sangita Ramsinh Rathod",
    "bloodgroup": "B+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village Name",
      "taluko": "Taluko Name",
      "district": "District Name",
      "pincode": 123456
    },
    "teachingStandard":"8B",
    "teacherCode":2,
    "password":"Sangita@123"
  }

  const teacher7A={
    "firstName": "Rajesh",
    "middleName": "Mahesh",
    "surname": "Shah",
    "fullName": "Rajesh Mahesh Shah",
    "fatherName": "Mahesh Shah",
    "motherName": "Anjali Shah",
    "birthDate": "1992-08-14",
    "email": "rajesh.shah@email.com",
    "gender": "Male",
    "mobile": 9867543210,
    "aadhar": 554567891125,
    "nameAsPerAadhar": "Rajesh Mahesh Shah",
    "bloodgroup": "A+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village B",
      "taluko": "Taluko B",
      "district": "District B",
      "pincode": 223456
    },
    "teachingStandard": "7A",
    "teacherCode": 2,
    "password": "Rajesh@123"
  }
  const teacher7B={
    "firstName": "Seema",
    "middleName": "Vinod",
    "surname": "Patel",
    "fullName": "Seema Vinod Patel",
    "fatherName": "Vinod Patel",
    "motherName": "Meena Patel",
    "birthDate": "1988-12-25",
    "email": "seema.patel@email.com",
    "gender": "Female",
    "mobile": 9876543211,
    "aadhar": 554567891126,
    "nameAsPerAadhar": "Seema Vinod Patel",
    "bloodgroup": "O+",
    "cast": "OBC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village C",
      "taluko": "Taluko C",
      "district": "District C",
      "pincode": 323456
    },
    "teachingStandard": "7B",
    "teacherCode": 3,
    "password": "Seema@123"
  }

  const teacher6A={
    "firstName": "Amit",
    "middleName": "Rakesh",
    "surname": "Joshi",
    "fullName": "Amit Rakesh Joshi",
    "fatherName": "Rakesh Joshi",
    "motherName": "Priti Joshi",
    "birthDate": "1985-05-15",
    "email": "amit.joshi@email.com",
    "gender": "Male",
    "mobile": 9876543212,
    "aadhar": 554567891127,
    "nameAsPerAadhar": "Amit Rakesh Joshi",
    "bloodgroup": "B+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village D",
      "taluko": "Taluko D",
      "district": "District D",
      "pincode": 423456
    },
    "teachingStandard": "6A",
    "teacherCode": 4,
    "password": "Amit@123"
  }

  const teacher6B={
    "firstName": "Manisha",
    "middleName": "Kiran",
    "surname": "Kapadia",
    "fullName": "Manisha Kiran Kapadia",
    "fatherName": "Kiran Kapadia",
    "motherName": "Jaya Kapadia",
    "birthDate": "1990-09-09",
    "email": "manisha.kapadia@email.com",
    "gender": "Female",
    "mobile": 9876543213,
    "aadhar": 554567891128,
    "nameAsPerAadhar": "Manisha Kiran Kapadia",
    "bloodgroup": "AB+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village E",
      "taluko": "Taluko E",
      "district": "District E",
      "pincode": 523456
    },
    "teachingStandard": "6B",
    "teacherCode": 5,
    "password": "Manisha@123"
  }

  const teacher5A= {
    "firstName": "Kiran",
    "middleName": "Ramesh",
    "surname": "Mehta",
    "fullName": "Kiran Ramesh Mehta",
    "fatherName": "Ramesh Mehta",
    "motherName": "Naina Mehta",
    "birthDate": "1987-04-20",
    "email": "kiran.mehta@email.com",
    "gender": "Male",
    "mobile": 9876543214,
    "aadhar": 554567891129,
    "nameAsPerAadhar": "Kiran Ramesh Mehta",
    "bloodgroup": "O+",
    "cast": "SC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village F",
      "taluko": "Taluko F",
      "district": "District F",
      "pincode": 623456
    },
    "teachingStandard": "5A",
    "teacherCode": 6,
    "password": "Kiran@123"
  }

  const teacher5B={
    "firstName": "Priya",
    "middleName": "Dinesh",
    "surname": "Desai",
    "fullName": "Priya Dinesh Desai",
    "fatherName": "Dinesh Desai",
    "motherName": "Leela Desai",
    "birthDate": "1991-11-05",
    "email": "priya.desai@email.com",
    "gender": "Female",
    "mobile": 9876543215,
    "aadhar": 554567891130,
    "nameAsPerAadhar": "Priya Dinesh Desai",
    "bloodgroup": "A+",
    "cast": "OBC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village G",
      "taluko": "Taluko G",
      "district": "District G",
      "pincode": 723456
    },
    "teachingStandard": "5B",
    "teacherCode": 7,
    "password": "Priya@123"
  }
  

  const teacher4A={
    "firstName": "Ravi",
    "middleName": "Mahesh",
    "surname": "Patel",
    "fullName": "Ravi Mahesh Patel",
    "fatherName": "Mahesh Govind Patel",
    "motherName": "Kavita Patel",
    "birthDate": "1990-06-14",
    "email": "ravi.patel@email.com",
    "gender": "Male",
    "mobile": 9876543201,
    "aadhar": 554567891131,
    "nameAsPerAadhar": "Ravi Mahesh Patel",
    "bloodgroup": "O+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village H",
      "taluko": "Taluko H",
      "district": "District H",
      "pincode": 823456
    },
    "teachingStandard": "4A",
    "teacherCode": 8,
    "password": "Ravi@123"
  }
  

  const teacher4B={
    "firstName": "Ankita",
    "middleName": "Rajesh",
    "surname": "Shah",
    "fullName": "Ankita Rajesh Shah",
    "fatherName": "Rajesh Kirit Shah",
    "motherName": "Meena Shah",
    "birthDate": "1988-02-22",
    "email": "ankita.shah@email.com",
    "gender": "Female",
    "mobile": 9876543202,
    "aadhar": 554567891132,
    "nameAsPerAadhar": "Ankita Rajesh Shah",
    "bloodgroup": "B+",
    "cast": "General",
    "religion": "Jain",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village I",
      "taluko": "Taluko I",
      "district": "District I",
      "pincode": 923456
    },
    "teachingStandard": "4B",
    "teacherCode": 9,
    "password": "Ankita@123"
  }
  

  const teacher3A={
    "firstName": "Kiran",
    "middleName": "Suresh",
    "surname": "Mehta",
    "fullName": "Kiran Suresh Mehta",
    "fatherName": "Suresh Vinod Mehta",
    "motherName": "Bhavna Mehta",
    "birthDate": "1993-12-08",
    "email": "kiran.mehta@email.com",
    "gender": "Female",
    "mobile": 9876543203,
    "aadhar": 554567891133,
    "nameAsPerAadhar": "Kiran Suresh Mehta",
    "bloodgroup": "AB+",
    "cast": "OBC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village J",
      "taluko": "Taluko J",
      "district": "District J",
      "pincode": 102345
    },
    "teachingStandard": "3A",
    "teacherCode": 10,
    "password": "Kiran@123"
  }
  
  const teacher3B={
    "firstName": "Vishal",
    "middleName": "Manoj",
    "surname": "Joshi",
    "fullName": "Vishal Manoj Joshi",
    "fatherName": "Manoj Dharmesh Joshi",
    "motherName": "Lata Joshi",
    "birthDate": "1989-03-19",
    "email": "vishal.joshi@email.com",
    "gender": "Male",
    "mobile": 9876543204,
    "aadhar": 554567891134,
    "nameAsPerAadhar": "Vishal Manoj Joshi",
    "bloodgroup": "O-",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village K",
      "taluko": "Taluko K",
      "district": "District K",
      "pincode": 112345
    },
    "teachingStandard": "3B",
    "teacherCode": 11,
    "password": "Vishal@123"
  }
  
  const teacher2A={
    "firstName": "Neha",
    "middleName": "Ravi",
    "surname": "Sharma",
    "fullName": "Neha Ravi Sharma",
    "fatherName": "Ravi Prakash Sharma",
    "motherName": "Anita Sharma",
    "birthDate": "1992-07-15",
    "email": "neha.sharma@email.com",
    "gender": "Female",
    "mobile": 9876543205,
    "aadhar": 554567891135,
    "nameAsPerAadhar": "Neha Ravi Sharma",
    "bloodgroup": "A+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village L",
      "taluko": "Taluko L",
      "district": "District L",
      "pincode": 122345
    },
    "teachingStandard": "2A",
    "teacherCode": 12,
    "password": "Neha@123"
  }
  
  const teacher2B={
    "firstName": "Anuj",
    "middleName": "Sanjay",
    "surname": "Verma",
    "fullName": "Anuj Sanjay Verma",
    "fatherName": "Sanjay Kumar Verma",
    "motherName": "Meera Verma",
    "birthDate": "1990-04-12",
    "email": "anuj.verma@email.com",
    "gender": "Male",
    "mobile": 9876543206,
    "aadhar": 554567891136,
    "nameAsPerAadhar": "Anuj Sanjay Verma",
    "bloodgroup": "B+",
    "cast": "OBC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village M",
      "taluko": "Taluko M",
      "district": "District M",
      "pincode": 132345
    },
    "teachingStandard": "2B",
    "teacherCode": 13,
    "password": "Anuj@123"
  }
  
  const teacher1A={
    "firstName": "Pooja",
    "middleName": "Mahendra",
    "surname": "Goyal",
    "fullName": "Pooja Mahendra Goyal",
    "fatherName": "Mahendra Goyal",
    "motherName": "Kamla Goyal",
    "birthDate": "1994-03-09",
    "email": "pooja.goyal@email.com",
    "gender": "Female",
    "mobile": 9876543207,
    "aadhar": 554567891137,
    "nameAsPerAadhar": "Pooja Mahendra Goyal",
    "bloodgroup": "O+",
    "cast": "General",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village N",
      "taluko": "Taluko N",
      "district": "District N",
      "pincode": 142345
    },
    "teachingStandard": "1A",
    "teacherCode": 14,
    "password": "Pooja@123"
  }
  
  const teacher1B={
    "firstName": "Arun",
    "middleName": "Vinod",
    "surname": "Jain",
    "fullName": "Arun Vinod Jain",
    "fatherName": "Vinod Kumar Jain",
    "motherName": "Rekha Jain",
    "birthDate": "1991-09-21",
    "email": "arun.jain@email.com",
    "gender": "Male",
    "mobile": 9876543208,
    "aadhar": 554567891138,
    "nameAsPerAadhar": "Arun Vinod Jain",
    "bloodgroup": "B-",
    "cast": "General",
    "religion": "Jain",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village O",
      "taluko": "Taluko O",
      "district": "District O",
      "pincode": 152345
    },
    "teachingStandard": "1B",
    "teacherCode": 15,
    "password": "Arun@123"
  }
  
  const teacher0={
    "firstName": "Kavita",
    "middleName": "Rajendra",
    "surname": "Chaudhary",
    "fullName": "Kavita Rajendra Chaudhary",
    "fatherName": "Rajendra Chaudhary",
    "motherName": "Geeta Chaudhary",
    "birthDate": "1995-08-18",
    "email": "kavita.chaudhary@email.com",
    "gender": "Female",
    "mobile": 9876543209,
    "aadhar": 554567891139,
    "nameAsPerAadhar": "Kavita Rajendra Chaudhary",
    "bloodgroup": "A-",
    "cast": "OBC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Teacher",
    "address": {
      "village": "Village P",
      "taluko": "Taluko P",
      "district": "District P",
      "pincode": 162345
    },
    "teachingStandard": "0",
    "teacherCode": 16,
    "password": "Kavita@123"
  }
  



  const admin={ 
    "firstName": "Jayant",
    "middleName": "Babubhai",
    "surname": "Lalwadiya",
    "fullName": "Jayant Babubhai Lalwadiya",
    "fatherName": "Jayant Lalwadiya",
    "motherName": "Shobhanaben Lalwadiya",
    "birthDate": "1974-07-11",
    "email": "yantlalwadiya@gmail.com",
    "gender": "Male",
    "mobile": 9824527603,
    "aadhar": 858547890123,
    "nameAsPerAadhar": "Jayant Babubhai Lalwadiya",
    "bloodgroup": "AB+",
    "cast": "SC",
    "religion": "Hindu",
    "physicallyHandicapped": "No",
    "role": "Admin",
    "address": {
      "village": "Village Name",
      "taluko": "Taluko Name",
      "district": "District Name",
      "pincode": 123456
    },
    
    "password":"Jayant@123"
  }


